version: '3.9'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/

  
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
